(ns mbs-se-pv.views.psm-names)

(def type-names {"A" "Stromstärke AC"
                 "Amp" "Stromstärke DC"
                 "EnclTmp" "Temperatur" ;"Gehäusetemperatur"
                 "EnvTmp" "Temperatur" ;"Umgebungstemperatur"
                 "HeatSinkTmp" "Temperatur" ;"Kühlkörpertemperatur"
                 "HorInsol" "Einstrahlung"
                 "Hz" "Frequenz"
                 "OpTmRs" "Betriebsstunden"
                 "PhV" "Spannung Phase"
                 "Ris" "Isolationswiderstand"
                 "RotPos" "Ausrichtung"
                 "RotSpd" "Umdrehungen"
                 "TmpSv" "Temperatur" ; "Generatortemperatur"
                 "TotVA" "Scheinleistung"
                 "TotVAr" "Blindleistung"
                 "TotW" "Wirkleistung"
                 "TotWh" "Ertrag"
                 "Vol" "Spannung"
                 "W" "Leistung"
                 "Watt" "Leistung"
                 "WdSpd" "Windgeschwindigkeit"
                 "AlmSt" "Fehler"})